Named Entities Identification
agarant/NLIWOD pull request #2
Opened 2017-04-04 08:36 UTC by Rawank

Changed the order of the pipelines' modules:
Determining named entities after combining phrases.

2017-04-04 10:44 UTC, agarant requested changes
The overall complexity is very high. Long functions, many nesting levels, long variable lifespans, etc. As a result, I have a hard time understanding what is the goal of your changes. Also, the indentation style is not consistent which makes it even harder to read. Please take the time to clean up this code so that it is more descriptive. Try to keep your functions short (<50 loc), avoid to have more than 1 or 2 nested levels, etc. There is also a significant amount of compiler errors that need to be addressed before it can be merged.

2017-04-04 10:44 UTC, agarant commented on qa.hawk/src/main/java/org/aksw/hawk/nlp/SentenceToSequence.java
> +				           namedEntityOrCombinedPhrase = checkNamedEntites(tempSubsequance2,q);
I think that this block of code is exactly the same as the one below, could you extract a function?

2017-04-04 10:44 UTC, agarant commented on qa.hawk/src/main/java/org/aksw/hawk/nlp/SentenceToSequence.java
> +				subsequance = Lists.newArrayList();
subsequance is never defined? Did you mean subsequence?

2017-04-04 10:44 UTC, agarant commented on qa.hawk/src/main/java/org/aksw/hawk/nlp/SentenceToSequence.java
>  		//remove quotation marks from the sentence, then send it to the combination algo
You changed a lot of things in the file, does the comment still describes what this function is doing?

2017-04-07 18:06 UTC, Rawank commented on qa.hawk/src/main/java/org/aksw/hawk/nlp/SentenceToSequence.java
>  		//remove quotation marks from the sentence, then send it to the combination algo
yes
each comment describes what that function or command do

2017-04-07 18:16 UTC, Rawank commented
Before change:
* Named entities can't be combined with other phrases because they are replaced by URIs in the question
* Hawk add query fragments based on the retrieved named entities and phrases from getLanguageToNamedEntites() & getLanguageToNounPhrases() 

After change:
*Named entities are identified BUT not replaced by URIs in the question
* Combination is done for all question phrases including NEs
* all combined phrases are added to getLanguageToNounPhrases() 
* Query fragments are added based on getLanguageToNounPhrases(), which contains NEs & CNNs

2017-04-11 01:00 UTC, merged